[package]
name = "day19"
version = "0.1.0"
authors = ["Chris Cavey <cicavey@visionistinc.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aoc = { path = "../aoc"}
regex = "1"
pcre2 = "0.1"